#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("AndroidWeather.Resource", IsApplication=true)]

namespace AndroidWeather
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int cloud = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int Icon = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int rain = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int snow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int sun = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int WeatherBG = 2130837509;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050001
			public const int cityText = 2131034113;
			
			// aapt resource value: 0x7f05000e
			public const int firstHour = 2131034126;
			
			// aapt resource value: 0x7f050010
			public const int firstHourWeather = 2131034128;
			
			// aapt resource value: 0x7f05001a
			public const int fourthHour = 2131034138;
			
			// aapt resource value: 0x7f05001c
			public const int fourthHourWeather = 2131034140;
			
			// aapt resource value: 0x7f050002
			public const int getWeatherButton = 2131034114;
			
			// aapt resource value: 0x7f05000f
			public const int imageViewFirst = 2131034127;
			
			// aapt resource value: 0x7f05001b
			public const int imageViewFourth = 2131034139;
			
			// aapt resource value: 0x7f050013
			public const int imageViewSecond = 2131034131;
			
			// aapt resource value: 0x7f050017
			public const int imageViewThird = 2131034135;
			
			// aapt resource value: 0x7f050003
			public const int linearLayout1 = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int linearLayout2 = 2131034116;
			
			// aapt resource value: 0x7f050007
			public const int linearLayout3 = 2131034119;
			
			// aapt resource value: 0x7f05000d
			public const int linearLayoutFirstHour = 2131034125;
			
			// aapt resource value: 0x7f050019
			public const int linearLayoutFourthHour = 2131034137;
			
			// aapt resource value: 0x7f05000b
			public const int linearLayoutHidden = 2131034123;
			
			// aapt resource value: 0x7f05000c
			public const int linearLayoutHoldsHourly = 2131034124;
			
			// aapt resource value: 0x7f050011
			public const int linearLayoutSecondHour = 2131034129;
			
			// aapt resource value: 0x7f050015
			public const int linearLayoutThirdHour = 2131034133;
			
			// aapt resource value: 0x7f050000
			public const int mainLayout = 2131034112;
			
			// aapt resource value: 0x7f05000a
			public const int progressBarHolder = 2131034122;
			
			// aapt resource value: 0x7f050012
			public const int secondHour = 2131034130;
			
			// aapt resource value: 0x7f050014
			public const int secondHourWeather = 2131034132;
			
			// aapt resource value: 0x7f050009
			public const int switchGPS = 2131034121;
			
			// aapt resource value: 0x7f050008
			public const int switchImperial = 2131034120;
			
			// aapt resource value: 0x7f05001d
			public const int tempText = 2131034141;
			
			// aapt resource value: 0x7f050006
			public const int textView1 = 2131034118;
			
			// aapt resource value: 0x7f050005
			public const int textView2 = 2131034117;
			
			// aapt resource value: 0x7f050016
			public const int thirdHour = 2131034134;
			
			// aapt resource value: 0x7f050018
			public const int thirdHourWeather = 2131034136;
			
			// aapt resource value: 0x7f05001e
			public const int weatherText = 2131034142;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int Main = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int MainDemo = 2130903041;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f040001
			public const int ApplicationName = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int Hello = 2130968576;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
	}
}
#pragma warning restore 1591
